version: "3"

services:
  db:
    container_name: tomcat-jmp-db
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=jpm_tomcat_local
     - POSTGRES_PASSWORD=jpm_tomcat_local
     - POSTGRES_DB=jpm_tomcat_local
    expose:
     - "5432"
    networks:
      - tomcat-jmp-net
  app:
    container_name: tomcat-jmp-app
    build: ./app
    expose:
     - "8081"
    networks:
      - tomcat-jmp-net
    links:
     - db
    environment:
     - JMP_DB_URL=postgresql://db:5432/jpm_tomcat_local
     - SERVER_PORT=8081
  lb:
    container_name: tomcat-jmp-lb
    build: ./nginx
    ports:
     - "8080:8080"
    networks:
      - tomcat-jmp-net
    links:
     - app

networks:
  tomcat-jmp-net:
    driver: bridge
